general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/hypr/wallpaper.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
}

label {
    monitor =
    text = cmd[update:100000] echo "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 0.9)
    font_size = 18
    font_family = SF Pro Display Bold, Noto Sans Bold
    position = 0, -15%
    halign = center
    valign = top
}

label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 0.9)
    font_size = 105
    font_family = SF Pro Display Bold, Noto Sans Bold
    position = 0, -16%
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 220, 42
    outline_thickness = 0
    dots_size = 0.28
    inner_color = rgba(44, 74, 62, 0.35)
    check_color = rgba(238, 252, 253, 0.6)
    fail_color = rgba(115, 79, 115, 0.8)
    fail_text = <span>$FAIL ($ATTEMPTS)</span>
    font_color = rgb(255, 255, 255)
    font_family = SF Pro Text Bold, Noto Sans Bold
    placeholder_text =
    hide_input = false
    fade_timeout = 0
    position = 0, -20%
    halign = center
    valign = center
}
