theme {
    style = Breeze
    color_scheme = /usr/share/color-schemes/BreezeLight.colors
    icon_theme = breeze
    font = Sans Serif
    font_size = 11
    font_fixed = monospace
    font_fixed_size = 11
}
